Terms
maximumJavascript/6-seniors-docs pull request #5
Opened 2022-10-25 06:39 UTC by Igorsml

Before

![image](https://user-images.githubusercontent.com/75610081/197700230-d0fbf513-a6e8-417e-85d6-c992f0ddef22.png)

After
![image](https://user-images.githubusercontent.com/75610081/197700517-6ecc9b12-221c-457c-941e-cb98c6cee0c4.png)

2022-10-25 06:47 UTC, maximumJavascript commented on src/docs/01.forStudent/03.terms.md
> +- **Отчет** - сообщение по строгому [шаблону](https://www.notion.so/214462a0dc9e4c859477255a60d0aa3e), отправляемое в назначенный срок перед встречей. Отправляются членами группы, для тех, кто хочет
ссылки на notion наш делать не надо

2022-10-25 06:48 UTC, maximumJavascript commented on src/docs/01.forStudent/03.terms.md
> +- **Event, Эвент** - итоговое представление любой встречи в [google календаре](https://calendar.google.com/calendar/u/0?cid=cnNzZmxsY2o3cGQxMTFsZzg0YnAzbzlndWNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) с:
не обязательно гугл календарь, тут возможно стоит написать "в google календаре или на любой подобной доске", ссылки на наши штуки 6Seniors тоже не нужны

2022-10-25 06:49 UTC, maximumJavascript commented on src/docs/01.forStudent/03.terms.md
> +- **Event, Эвент** - итоговое представление любой встречи в [google календаре](https://calendar.google.com/calendar/u/0?cid=cnNzZmxsY2o3cGQxMTFsZzg0YnAzbzlndWNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) с:
все наши ссылки максимум будут на стартовой странице

2022-10-25 06:49 UTC, maximumJavascript requested changes
.

2022-10-25 06:54 UTC, ihaveataletotell commented on src/docs/01.forStudent/03.terms.md
> +    [[08.meetings|Встречи]] и
эти ссылки норм, внутри доки ссылки на соседние страницы кайф

2022-10-25 06:54 UTC, ihaveataletotell commented on src/docs/01.forStudent/03.terms.md
> +    [[08.meetings|Встречи]] и
это я тоже, просто акк другой)

2022-10-27 07:50 UTC, Igorsml commented on src/docs/01.forStudent/03.terms.md
> +    [[08.meetings|Встречи]] и
Такс, подправил термины, вчера стенографировал запись видео, продолжу ковырять

2022-10-27 13:32 UTC, maximumJavascript commented on src/docs/01.forStudent/03.terms.md
> +- **Event, Эвент** - итоговое представление любой встречи в google календаре в google календаре или на любой подобной доск с:
игорь 🥲 ну это слишком плохо

2022-10-27 13:33 UTC, maximumJavascript commented on src/docs/01.forStudent/03.terms.md
> +- **Отчет** - сообщение по строгому шаблону, отправляемое в назначенный срок перед встречей. Отправляются членами группы, для тех, кто хочет вернуться в группу после исключения отправка отчётов обяза
иигорь🥲

2022-10-31 09:09 UTC, Igorsml commented on src/docs/01.forStudent/03.terms.md
> +- **Отчет** - сообщение по строгому шаблону, отправляемое в назначенный срок перед встречей. Отправляются членами группы, для тех, кто хочет вернуться в группу после исключения отправка отчётов обяза
Дубль 3 🥲, список изменений [тут](https://github.com/maximumJavascript/6-seniors-docs/pull/5/commits/da989aad7c779898e697022754706020bb21a8ca)

2022-11-02 14:03 UTC, merged